---
- name: "Get current size of {{ item.mount_path }}"
  ansible.builtin.shell: "/usr/sbin/lvdisplay {{ item.lv_path }} | grep 'LV Size (Mbytes)' | awk '{print $4}'"
  register: ignite_ux_current_lv_size
  changed_when: false

- name: "Resize logical partitions block"
  when: ignite_ux_current_lv_size.stdout | int < item.lv_size | int
  block:
    - name: "Ensure logical partition is correct size"
      ansible.builtin.command: "/usr/sbin/lvextend -L {{ item.lv_size }} {{ item.lv_path }}"

    - name: "Ensure VXFS claims new space"
      ansible.builtin.command: "/usr/sbin/fsadm -F vxfs -b {{ item.lv_size }}M {{ item.mount_path }}"
