namespace: iambryant

name: hpux

version: 1.0.0

readme: README.md

authors:
  - iambryant

description: This collection includes roles for automating common tasks in HP-UX.

license:
  - MIT

license_file: 'LICENSE'

tags:
  - hpux

dependencies:
  community.general: ">=8.0.0"

repository: https://github.com/iambryant/ansible-collection-hpux

documentation: https://github.com/iambryant/ansible-collection-hpux

homepage: http://example.com

issues: https://github.com/iambryant/ansible-collection-hpux/issues

build_ignore: []
