---
- name: "Check if Integrity VM is installed"
  ansible.builtin.command: "/opt/hpvm/bin/hpvminfo"
  register: hpvm_check
  failed_when: false
  changed_when: false

- name: "Perform installation and reboot sequence"
  when: "'Running on an HPVM host' not in hpvm_check.stdout"
  block:
    - name: "Install Integrity VM"
      ansible.builtin.command: "/usr/sbin/swinstall -x autoreboot=true -s {{ hpux_sdux_server }}:{{ hpux_sdux_server_path }} BB068AA VirtualBase"
      async: 300
      poll: 0

    - name: "Wait for system to reboot"
      ansible.builtin.wait_for_connection:
        delay: 300
        timeout: 600

    - name: "Verify Integrity VM is installed"
      ansible.builtin.command: "/opt/hpvm/bin/hpvminfo"
      register: integrity_verify
      until: "'Running on an HPVM host' in integrity_verify.stdout"
      retries: 10
      delay: 10
      failed_when: "'Running on an HPVM host' not in integrity_verify.stdout"
      changed_when: false

- name: "Check if vSwitch {{ integrity_vswitch_name }} exists"
  ansible.builtin.command: "/opt/hpvm/bin/hpvmnet -v -S {{ integrity_vswitch_name }}"
  register: integrity_vswitch_check
  failed_when: false
  changed_when: false

- name: "Configure vSwitch"
  when: integrity_vswitch_check.rc != 0
  block:
    - name: "Create vSwitch {{ integrity_vswitch_name }} on lan{{ integrity_vswitch_lan }}"
      ansible.builtin.command: "/opt/hpvm/bin/hpvmnet -c -S {{ integrity_vswitch_name }} -n {{ integrity_vswitch_lan }}"

    - name: "Start vSwitch {{ integrity_vswitch_name }}"
      ansible.builtin.command: "/opt/hpvm/bin/hpvmnet -b -S {{ integrity_vswitch_name }}"

- name: "Manage Integrity VMs"
  include_tasks: create_vms.yml
  when: integrity_guests is defined
