---
ignite_staging_dir: "/var/tmp"
ignite_depot_filename: ""

ignite_logical_volumes:
  - lv_path: "/dev/vg00/lvol8"
    mount_path: "/var"
    lv_size: 9216
  - lv_path: "/dev/vg00/lvol6"
    mount_path: "/opt"
    lv_size: 2048
