---
hpux_staging_dir: "/var/tmp"
ignite_ux_depot: ""

ignite_ux_logical_volumes:
  - lv_path: "/dev/vg00/lvol6"
    mount_path: "/opt"
    lv_size: 8192
  - lv_path: "/dev/vg00/lvol8"
    mount_path: "/var"
    lv_size: 16384

ignite_ux_user_files: []
ignite_ux_user_templates: []
